# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2c6e4780a5561802bb800d0d28d827340cb11abe3724addffc2a337ea1edd89b50f63376dcb8c3c124cbe8e5680e77e315cd1a531b3723d2a7bde1ff798139be

test:
  secret_key_base: e2be88142bf407d68cb28b6901a3e20ccf3f4e0c6d776481ba75913ffac55d62df3588383e44cdaf3b47bed2f5be6d9d6d0c7e51ef4fb1876de2232b3f854156

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
